services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      - db
      - cache

  db:
    image: postgres:latest
    container_name: db
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: cache
    ports:
      - "${CACHE_PORT:-6379}:${CACHE_PORT:-6379}"

volumes:
  postgres_data:
